module.exports = [
  {
    "id": "abc123def456ghi",
    "title": "Software Engineer",
    "description": "We are looking for a passionate software engineer to join our team. Responsibilities include developing web applications, maintaining and scaling systems, and working closely with cross-functional teams.",
    "category": "Engineering",
    "location": "Jakarta, Indonesia",
    "position": "full-time",
    "requirements": ['S1-Teknik Informatika', 'S1-Sistem Informasi'],
    "type": "recruitment",
    "status": "open",
  },
  {
    "id": "xyz987uvw654rst",
    "title": "Marketing Manager",
    "description": "We are looking for a dynamic marketing manager to lead our team. Responsibilities include developing marketing strategies, managing campaigns, and analyzing market trends.",
    "category": "Marketing",
    "location": "Bali, Indonesia",
    "position": "full-time",
    "type": "recruitment",
    "requirements": ['S1-Teknik Informatika', 'S1-Sistem Informasi'],
    "status": "pending",
  },
  {
    "id": "jkl456mno789pqr",
    "title": "UI/UX Designer",
    "description": "Join our team as a UI/UX designer to create user-friendly interfaces and provide design solutions that improve the overall user experience across all platforms.",
    "category": "Design",
    "location": "Surabaya, Indonesia",
    "position": "full-time",
    "type": "assessment",
    "requirements": ['S1-Teknik Informatika', 'S1-Sistem Informasi'],
    "status": "closed",
  },
  {
    "id": "stu321vwx654yzp",
    "title": "Human Resources Assistant",
    "description": "We are looking for a detail-oriented HR Assistant to support the HR department with recruitment, employee engagement, and administrative tasks.",
    "category": "Human Resources",
    "location": "Jakarta, Indonesia",
    "position": "full-time",
    "type": "recruitment",
    "requirements": ['S1-Teknik Informatika', 'S1-Sistem Informasi'],
    "status": "open",
  },
  {
    "id": "uvw789xyz123def",
    "title": "Data Scientist",
    "description": "We are looking for a skilled data scientist to analyze and interpret complex data to help guide business decisions. Proficiency in Python, SQL, and machine learning is required.",
    "category": "Data Science",
    "location": "Bandung, Indonesia",
    "position": "full-time",
    "type": "assessment",
    "requirements": ['S1-Teknik Informatika', 'S1-Sistem Informasi'],
    "status": "open",
  }
]
